name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1.10.1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Create release
        uses: ncipollo/release-action@v1.16.0
        with:
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          tag: ${{ steps.semver.outputs.next }}
          body: Changelog
          token: ${{ github.token }}
